#!/usr/bin/env python3
"""MMSA task bridge -- guard suite and mutation harness.

Written in Python rather than .mjs for one reason: these checks must parse the
workflow as YAML, and this repository carries no Node YAML dependency while
PyYAML is already present (tools/md2report.py is Python). Parsing the file
rather than grepping it is what makes the checks mean anything -- a regex over
raw text cannot tell a clause inside `if:` from the same words in a comment.

Run from the repository root:  python3 tools/automation-verify/mmsa_task_bridge_guards.py
"""
import copy, io, re, sys, yaml

WORKFLOW = ".github/workflows/mmsa-task-bridge.yml"
PROMPT = "docs/automation/mmsa-task-bridge-routine-prompt.md"
OWNER_ID = 293311955

passed = failed = 0

def check(label, fn):
    global passed, failed
    if callable(getattr(fn, "__call__", None)) and hasattr(fn, "__await__"):
        raise AssertionError("check body must not be a coroutine: " + label)
    try:
        ok = fn()
    except Exception as exc:                      # noqa: BLE001
        ok, label = False, "%s  [raised %s]" % (label, exc)
    if ok:
        passed += 1; print("  PASS  " + label)
    else:
        failed += 1; print("  FAIL  " + label)
    return ok

def load(path):
    return io.open(path, encoding="utf-8").read()

def wf(text=None):
    return yaml.safe_load(text if text is not None else load(WORKFLOW))

def job(d):
    return d["jobs"]["fire"]

def cond(d):
    return " ".join(job(d)["if"].split())

def steps_text(text):
    return text[text.index("    steps:"):]

# --- the guards, each written so a mutation can break exactly one -------------

def g_trigger_created_only(d, _t, _p):
    return (d.get("on") or d.get(True))["issue_comment"]["types"] == ["created"]

def g_issues_only(d, _t, _p):
    return "github.event.issue.pull_request == null" in cond(d)

def g_owner_numeric_id(d, _t, _p):
    return ("github.event.comment.user.id == %d" % OWNER_ID) in cond(d)

def g_actor_is_user(d, _t, _p):
    return "github.event.comment.user.type == 'User'" in cond(d)

def g_association_allowlist(d, _t, _p):
    return 'fromJSON(\'["OWNER","MEMBER","COLLABORATOR"]\')' in cond(d)

def g_trigger_phrase_prefix(d, _t, _p):
    return "startsWith(github.event.comment.body, '/mmsa-task')" in cond(d)

def g_loop_guard_marker(d, _t, _p):
    return "!contains(github.event.comment.body, 'Generated by [Claude Code]')" in cond(d)

def g_no_dual_claude_dispatch(d, _t, p):
    return ("!contains(github.event.comment.body, '@claude')" in cond(d)
            and "or `@claude`" in p)

def g_numeric_ids_before_gh(_d, _t, p):
    validation = '[[ "$comment_id" =~ ^[0-9]+$ ]] && [[ "$issue_number" =~ ^[0-9]+$ ]]'
    first_gh = p.index('comment_json=$(gh api')
    return (validation in p[:first_gh]
            and 'gh api "repos/Madrasatul-Muslimeen/Madrasatul-Muslimeen.github.io/issues/comments/${comment_id}"' in p
            and 'gh api "repos/Madrasatul-Muslimeen/Madrasatul-Muslimeen.github.io/issues/${issue_number}"' in p)

def g_concurrency_per_comment(d, _t, _p):
    c = d.get("concurrency") or {}
    return "${{ github.event.comment.id }}" in str(c.get("group", "")) and c.get("cancel-in-progress") is False

def g_permissions_narrow(d, _t, _p):
    return d.get("permissions") == {"contents": "read", "issues": "write"}

def g_claim_step_present(d, _t, _p):
    s = [x for x in job(d)["steps"] if x.get("id") == "claim"]
    if not s:
        return False
    run = s[0]["run"]
    return "201)" in run and "200)" in run and "claimed=true" in run and "claimed=false" in run

def g_fire_gated_on_claim(d, _t, _p):
    s = [x for x in job(d)["steps"] if x.get("id") == "fire"]
    return bool(s) and "steps.claim.outputs.claimed == 'true'" in s[0].get("if", "")

def g_body_never_in_a_step(_d, t, _p):
    return "github.event.comment.body" not in steps_text(t)

def g_token_from_env(_d, t, _p):
    return re.search(r"Bearer \$ROUTINE_FIRE_TOKEN", t) is not None

def g_prompt_six_checks(_d, _t, p):
    return "all six" in p and "issue_url" in p and "not a pull request" in p

def g_prompt_protected_paths(_d, _t, p):
    return "is NOT authorization to touch it" in p and "firestore.rules" in p and ".github/workflows/" in p

def g_prompt_no_version_bump(_d, _t, p):
    return "NEVER increment the application version" in p

def g_prompt_no_merge_deploy(_d, _t, p):
    return "never merge, and never claim an approval" in p.lower() or "never merge, and never claim an approval" in p

GUARDS = [
    ("trigger is `created` only (an edit cannot re-fire)", g_trigger_created_only),
    ("ISSUES ONLY -- a PR conversation cannot dispatch", g_issues_only),
    ("gate uses the Owner's NUMERIC id", g_owner_numeric_id),
    ("gate requires actor type User", g_actor_is_user),
    ("gate uses the association allow-list", g_association_allowlist),
    ("trigger phrase must be a PREFIX, not merely contained", g_trigger_phrase_prefix),
    ("loop guard: Claude attribution marker refused", g_loop_guard_marker),
    ("mixed @claude command cannot dispatch both workflows", g_no_dual_claude_dispatch),
    ("untrusted numeric IDs validated before quoted gh calls", g_numeric_ids_before_gh),
    ("concurrency keyed on comment id, cancel-in-progress false", g_concurrency_per_comment),
    ("permissions are exactly contents:read + issues:write", g_permissions_narrow),
    ("durable claim step handles 201 and 200 distinctly", g_claim_step_present),
    ("fire is gated on the claim succeeding", g_fire_gated_on_claim),
    ("comment BODY appears in no step (task text cannot be sent)", g_body_never_in_a_step),
    ("token is read from env, not interpolated into the command", g_token_from_env),
    ("prompt verifies six things incl. issue/repo and not-a-PR", g_prompt_six_checks),
    ("prompt forbids protected paths and says a filename is not authorization", g_prompt_protected_paths),
    ("prompt forbids incrementing the application version", g_prompt_no_version_bump),
    ("prompt forbids merge/deploy/approval claims", g_prompt_no_merge_deploy),
]

print("==== MMSA task bridge guards ====")
text = load(WORKFLOW); prompt = load(PROMPT); doc = wf(text)
for label, fn in GUARDS:
    check(label, lambda fn=fn: fn(doc, text, prompt))

# --- mutations: every guard must be able to FAIL ------------------------------
print()
print("==== mutations (each must be CAUGHT) ====")

class AnchorError(Exception):
    """The mutation could not be applied -- a finding about the HARNESS."""


def mutate_text(old, new):
    # THE ANCHOR MUST BE UNIQUE, and that is not fussiness -- it is this suite's
    # own first finding. `types: [created]` occurs twice in the workflow: once in
    # the header PROSE explaining the choice, and once as the real YAML key. With
    # a `replace(..., 1)` the mutation edited the COMMENT, the YAML was untouched,
    # the guard correctly still passed, and the run reported UNPROVEN -- a finding
    # about the harness, not about the guard. A non-unique anchor cannot prove
    # anything, so it is refused by name rather than silently taking the first hit.
    n = text.count(old)
    if n != 1:
        raise AnchorError("anchor is not unique (%d occurrences): %r" % (n, old[:60]))
    return text.replace(old, new, 1)

MUTATIONS = [
    ("mixed @claude command is accepted by the bridge", g_no_dual_claude_dispatch,
     lambda: mutate_text("      !contains(github.event.comment.body, '@claude')", "      true"), None),
    ("untrusted comment ID reaches gh before validation", g_numeric_ids_before_gh,
     None, lambda: prompt.replace('[[ "$comment_id" =~ ^[0-9]+$ ]] && [[ "$issue_number" =~ ^[0-9]+$ ]]', 'true')),
    ("the issues-only clause is dropped", g_issues_only,
     lambda: mutate_text("github.event.issue.pull_request == null &&\n      ", ""), None),
    ("the trigger fires on edited comments too", g_trigger_created_only,
     lambda: mutate_text("    types: [created]  ", "    types: [created, edited]  "), None),
    ("the gate matches a LOGIN instead of the numeric id", g_owner_numeric_id,
     lambda: mutate_text("github.event.comment.user.id == 293311955",
                         "github.event.comment.user.login == 'AAAsapp'"), None),
    ("the trigger phrase is merely CONTAINED, not a prefix", g_trigger_phrase_prefix,
     lambda: mutate_text("startsWith(github.event.comment.body, '/mmsa-task')",
                         "contains(github.event.comment.body, '/mmsa-task')"), None),
    ("the durable claim step is removed", g_claim_step_present,
     lambda: re.sub(r"      - name: Claim this comment before firing.*?(?=      - name: Fire the routine)",
                    "", text, flags=re.S), None),
    ("fire stops being gated on the claim", g_fire_gated_on_claim,
     lambda: mutate_text(" && steps.claim.outputs.claimed == 'true'\n", "\n"), None),
    ("permissions are widened to contents: write", g_permissions_narrow,
     lambda: mutate_text("  contents: read\n  issues: write", "  contents: write\n  issues: write"), None),
    ("the comment BODY is passed into a step", g_body_never_in_a_step,
     lambda: mutate_text("          REPO: ${{ github.repository }}\n          ISSUE_NUMBER:",
                         "          REPO: ${{ github.repository }}\n          BODY: ${{ github.event.comment.body }}\n          ISSUE_NUMBER:"), None),
    ("the token is interpolated into the curl command", g_token_from_env,
     lambda: mutate_text('Bearer $ROUTINE_FIRE_TOKEN', 'Bearer ${{ secrets.ROUTINE_FIRE_TOKEN }}'), None),
    ("the prompt lets a named filename authorize a protected path", g_prompt_protected_paths,
     None, lambda: prompt.replace("is NOT authorization to touch it", "is authorization to touch it")),
    ("the prompt allows a version bump", g_prompt_no_version_bump,
     None, lambda: prompt.replace("NEVER increment the application version", "You may increment the application version")),
    ("the prompt drops the issue/repo and not-a-PR verification", g_prompt_six_checks,
     None, lambda: prompt.replace("all six", "all four")),
]

caught = unproven = anchor_errors = 0
for label, guard, wf_mut, pr_mut in MUTATIONS:
    # An anchor that does not apply is a HARNESS defect and is reported as one.
    # Folding it into the `except` below would print CAUGHT for a mutation that
    # never reached the file -- the exact false green this suite exists to refuse.
    try:
        mtext = wf_mut() if wf_mut else text
        mprompt = pr_mut() if pr_mut else prompt
    except AnchorError as exc:
        anchor_errors += 1
        print("  ERROR     %s  <-- mutation NOT APPLIED: %s" % (label, exc))
        continue
    try:
        mdoc = wf(mtext)
        still_true = guard(mdoc, mtext, mprompt)
    except Exception as exc:                      # noqa: BLE001
        still_true = False                         # a mutation that breaks parsing is also caught
        label += "  [guard raised %s]" % type(exc).__name__
    if still_true:
        unproven += 1; print("  UNPROVEN  %s  <-- the guard did NOT catch this" % label)
    else:
        caught += 1; print("  CAUGHT    %s" % label)

# positive control: the harness must report the unmutated file as healthy
print()
control = all(fn(doc, text, prompt) for _, fn in GUARDS)
if control:
    print("  PASS  POSITIVE CONTROL: every guard passes on the real, unmutated files")
    passed += 1
else:
    print("  FAIL  POSITIVE CONTROL: a guard fails on the real files")
    failed += 1

print()
print("==== MMSA task bridge guards: %d passed, %d failed | mutations: %d caught, %d unproven, %d not applied ====" %
      (passed, failed, caught, unproven, anchor_errors))
sys.exit(1 if (failed or unproven or anchor_errors) else 0)
