#!/usr/bin/env python3
"""MMSA task bridge -- guard suite and mutation harness.

Written in Python rather than .mjs for one reason: these checks must parse the
workflow as YAML, and this repository carries no Node YAML dependency while
PyYAML is already present (tools/md2report.py is Python). Parsing the file
rather than grepping it is what makes the checks mean anything -- a regex over
raw text cannot tell a clause inside `if:` from the same words in a comment.

Run from the repository root:  python3 tools/automation-verify/mmsa_task_bridge_guards.py
"""
import copy, io, re, sys, yaml

WORKFLOW = ".github/workflows/mmsa-task-bridge.yml"
PROMPT = "docs/automation/mmsa-task-bridge-routine-prompt.md"
CLAUDE_WF = ".github/workflows/claude.yml"
# Mutable so the claude.yml-side guards can be mutation-proven like every other
# guard. A guard reading straight from disk cannot be made to fail, and a guard
# that cannot be made to fail has earned nothing.
CLAUDE_TEXT = None
OWNER_ID = 293311955

passed = failed = 0

def check(label, fn):
    global passed, failed
    if callable(getattr(fn, "__call__", None)) and hasattr(fn, "__await__"):
        raise AssertionError("check body must not be a coroutine: " + label)
    try:
        ok = fn()
    except Exception as exc:                      # noqa: BLE001
        ok, label = False, "%s  [raised %s]" % (label, exc)
    if ok:
        passed += 1; print("  PASS  " + label)
    else:
        failed += 1; print("  FAIL  " + label)
    return ok

def load(path):
    return io.open(path, encoding="utf-8").read()

def wf(text=None):
    return yaml.safe_load(text if text is not None else load(WORKFLOW))

def job(d):
    return d["jobs"]["fire"]

def cond(d):
    return " ".join(job(d)["if"].split())

def steps_text(text):
    return text[text.index("    steps:"):]

# --- the guards, each written so a mutation can break exactly one -------------

def g_trigger_created_only(d, _t, _p):
    return (d.get("on") or d.get(True))["issue_comment"]["types"] == ["created"]

def g_issues_only(d, _t, _p):
    return "github.event.issue.pull_request == null" in cond(d)

def g_owner_numeric_id(d, _t, _p):
    return ("github.event.comment.user.id == %d" % OWNER_ID) in cond(d)

def g_actor_is_user(d, _t, _p):
    return "github.event.comment.user.type == 'User'" in cond(d)

def g_association_allowlist(d, _t, _p):
    return 'fromJSON(\'["OWNER","MEMBER","COLLABORATOR"]\')' in cond(d)

def g_trigger_phrase_prefix(d, _t, _p):
    return "startsWith(github.event.comment.body, '/mmsa-task')" in cond(d)

def g_loop_guard_marker(d, _t, _p):
    return "!contains(github.event.comment.body, 'Generated by [Claude Code]')" in cond(d)

def g_concurrency_per_comment(d, _t, _p):
    c = d.get("concurrency") or {}
    return "${{ github.event.comment.id }}" in str(c.get("group", "")) and c.get("cancel-in-progress") is False

def g_permissions_narrow(d, _t, _p):
    return d.get("permissions") == {"contents": "read", "issues": "write"}

def g_claim_step_present(d, _t, _p):
    s = [x for x in job(d)["steps"] if x.get("id") == "claim"]
    if not s:
        return False
    run = s[0]["run"]
    return "201)" in run and "200)" in run and "claimed=true" in run and "claimed=false" in run

def g_fire_gated_on_claim(d, _t, _p):
    s = [x for x in job(d)["steps"] if x.get("id") == "fire"]
    return bool(s) and "steps.claim.outputs.claimed == 'true'" in s[0].get("if", "")

def g_body_never_in_a_step(_d, t, _p):
    return "github.event.comment.body" not in steps_text(t)

def g_token_from_env(_d, t, _p):
    return re.search(r"Bearer \$ROUTINE_FIRE_TOKEN", t) is not None

def g_prompt_six_checks(_d, _t, p):
    return "all six" in p and "issue_url" in p and "not a pull request" in p

def g_prompt_six_checks_no_stale_count(_d, _t, p):
    # THE ORIGINAL GUARD HAD A BLIND SPOT AND THE REVIEW FOUND IT.
    # g_prompt_six_checks asserts "all six" is PRESENT. It says nothing about a
    # surviving "all four" elsewhere in the same file -- and one survived, three
    # paragraphs below, telling the Routine to proceed "once all four checks
    # pass". A guard that only looks for the new wording cannot see the old
    # wording it replaced. Asserting the ABSENCE is what makes the rename real.
    return "all four" not in p and "four checks" not in p

def g_prompt_validates_ids_before_use(_d, _t, p):
    # The payload is untrusted and its ids are placed inside a shell command,
    # so their SHAPE must be checked before a command is built, not after.
    return ("^[0-9]{1,20}$" in p
            and "Step 0" in p
            and "before constructing a single command" in p.lower()
                or "before a command is built" in p.lower()
            ) and "^[0-9]{1,20}$" in p and "Step 0" in p

def g_prompt_quotes_gh_arguments(_d, _t, p):
    # Every gh invocation in the prompt must pass the endpoint after `--` and
    # quoted, so no value can be read as an option to gh.
    calls = re.findall(r"gh api[^\n`]*", p)
    return bool(calls) and all(c.startswith('gh api -- "') for c in calls)

def g_prompt_no_raw_placeholder_in_command(_d, _t, p):
    # The old form substituted <comment_id> straight into the command text.
    # ONE FORM THROUGHOUT: after Step 0 validates them, the two ids appear only
    # as the shell variables it bound. A raw <placeholder> surviving anywhere --
    # even in a string being COMPARED rather than executed -- means some part of
    # the prompt still reads the payload's own field, and the next reader cannot
    # tell which parts were validated.
    return "<comment_id>" not in p and "<issue_number>" not in p

def g_prompt_forbids_emitting_either_trigger(_d, _t, p):
    return "must never contain the text `/mmsa-task`" in p and "`@claude`" in p

def g_bridge_excludes_claude_mention(_d, _t, _p):
    return "!contains(github.event.comment.body, '@claude')" in cond(_d)

def g_claude_wf_excludes_bridge_phrase(_d, _t, _p):
    # The OTHER workflow's side of the exclusion. Parsed, not grepped.
    c = yaml.safe_load(CLAUDE_TEXT)
    j = list(c["jobs"].values())[0]
    return "!startsWith(github.event.comment.body, '/mmsa-task')" in " ".join(j["if"].split())

def _bridge_admits(body, bridge_if):
    """Model the bridge's body-related clauses against a candidate comment."""
    ok = True
    if "startsWith(github.event.comment.body, '/mmsa-task')" in bridge_if:
        ok = ok and body.startswith("/mmsa-task")
    elif "contains(github.event.comment.body, '/mmsa-task')" in bridge_if:
        ok = ok and "/mmsa-task" in body
    if "!contains(github.event.comment.body, '@claude')" in bridge_if:
        ok = ok and "@claude" not in body
    return ok

def g_mixed_command_fires_neither(_d, _t, _p):
    # The property itself, evaluated rather than described: for a comment that
    # carries BOTH phrases, each workflow's own exclusion must reject it.
    body = "/mmsa-task please do the thing, cc @claude"
    bridge_ok = _bridge_admits(body, cond(_d))
    c = yaml.safe_load(CLAUDE_TEXT)
    j = list(c["jobs"].values())[0]
    claude_if = " ".join(j["if"].split())
    claude_ok = ("@claude" in body
                 and not (("!startsWith(github.event.comment.body, '/mmsa-task')" in claude_if)
                          and body.startswith("/mmsa-task")))
    return (not bridge_ok) and (not claude_ok)

MALICIOUS_IDS = [
    "123 --method DELETE",        # an extra word becomes an OPTION to gh
    "123 -X DELETE",
    "-X",                         # a bare option
    "--jq .",                     # a long option
    "123; rm -rf /",              # command separator
    "123 && echo owned",
    "123 | tee /tmp/x",
    "$(id)",                      # command substitution
    "`id`",
    "123\n456",                   # embedded newline
    "123 456",                    # embedded space
    "../../etc/passwd",           # path traversal
    "12'3",                       # quote break-out
    '12"3',
    "+123", "-123", "1.23", "0x7b", "1e3",   # numeric-looking but not digits
    "", " ", "123 ",
    "1" * 21,                     # over the length bound
]
VALID_IDS = ["1", "123", "5746298072", "1" * 20]

def g_prompt_id_regex_rejects_malicious(_d, _t, p):
    """Run the prompt's OWN stated rule against hostile values.

    HONEST SCOPE, stated rather than implied: this proves the RULE the prompt
    specifies rejects these inputs. It does not prove a Routine obeys the
    prompt -- no test here can, because the Routine is a model reading prose.
    What it does buy is that the rule cannot silently weaken: change the
    pattern in the prompt and this fails.
    """
    m = re.search(r"\*\*`(\^\[0-9\]\{1,20\}\$)`\*\*", p)
    if not m:
        return False
    rx = re.compile(m.group(1))
    # `$` in Python also matches before a trailing newline -- that is exactly
    # the "123\n456" case, so fullmatch-style anchoring is asserted explicitly.
    if any(rx.match(v) and "\n" not in v and rx.fullmatch(v) for v in MALICIOUS_IDS):
        return False
    if any(rx.fullmatch(v) and "\n" in v for v in MALICIOUS_IDS):
        return False
    return all(rx.fullmatch(v) for v in VALID_IDS)

def g_prompt_protected_paths(_d, _t, p):
    return "is NOT authorization to touch it" in p and "firestore.rules" in p and ".github/workflows/" in p

def g_prompt_no_version_bump(_d, _t, p):
    return "NEVER increment the application version" in p

def g_prompt_no_merge_deploy(_d, _t, p):
    return "never merge, and never claim an approval" in p.lower() or "never merge, and never claim an approval" in p

GUARDS = [
    ("trigger is `created` only (an edit cannot re-fire)", g_trigger_created_only),
    ("ISSUES ONLY -- a PR conversation cannot dispatch", g_issues_only),
    ("gate uses the Owner's NUMERIC id", g_owner_numeric_id),
    ("gate requires actor type User", g_actor_is_user),
    ("gate uses the association allow-list", g_association_allowlist),
    ("trigger phrase must be a PREFIX, not merely contained", g_trigger_phrase_prefix),
    ("loop guard: Claude attribution marker refused", g_loop_guard_marker),
    ("concurrency keyed on comment id, cancel-in-progress false", g_concurrency_per_comment),
    ("permissions are exactly contents:read + issues:write", g_permissions_narrow),
    ("durable claim step handles 201 and 200 distinctly", g_claim_step_present),
    ("fire is gated on the claim succeeding", g_fire_gated_on_claim),
    ("comment BODY appears in no step (task text cannot be sent)", g_body_never_in_a_step),
    ("token is read from env, not interpolated into the command", g_token_from_env),
    ("prompt verifies six things incl. issue/repo and not-a-PR", g_prompt_six_checks),
    ("prompt carries NO stale `all four` wording", g_prompt_six_checks_no_stale_count),
    ("prompt validates ids as digits-only BEFORE building a command", g_prompt_validates_ids_before_use),
    ("every `gh api` in the prompt is quoted and passed after `--`", g_prompt_quotes_gh_arguments),
    ("prompt never substitutes a raw placeholder into a command", g_prompt_no_raw_placeholder_in_command),
    ("prompt forbids emitting EITHER trigger phrase", g_prompt_forbids_emitting_either_trigger),
    ("the prompt's id rule rejects 23 hostile values and admits 4 real ones", g_prompt_id_regex_rejects_malicious),
    ("bridge refuses a comment containing `@claude`", g_bridge_excludes_claude_mention),
    ("claude.yml refuses a comment starting with `/mmsa-task`", g_claude_wf_excludes_bridge_phrase),
    ("a MIXED `/mmsa-task ... @claude` comment fires NEITHER", g_mixed_command_fires_neither),
    ("prompt forbids protected paths and says a filename is not authorization", g_prompt_protected_paths),
    ("prompt forbids incrementing the application version", g_prompt_no_version_bump),
    ("prompt forbids merge/deploy/approval claims", g_prompt_no_merge_deploy),
]

print("==== MMSA task bridge guards ====")
text = load(WORKFLOW); prompt = load(PROMPT); doc = wf(text)
claude_text = load(CLAUDE_WF)
CLAUDE_TEXT = claude_text
for label, fn in GUARDS:
    check(label, lambda fn=fn: fn(doc, text, prompt))

# --- mutations: every guard must be able to FAIL ------------------------------
print()
print("==== mutations (each must be CAUGHT) ====")

class AnchorError(Exception):
    """The mutation could not be applied -- a finding about the HARNESS."""


def mutate_claude(old, new):
    n = claude_text.count(old)
    if n != 1:
        raise AnchorError("claude.yml anchor is not unique (%d occurrences): %r" % (n, old[:60]))
    return claude_text.replace(old, new, 1)


def mutate_text(old, new):
    # THE ANCHOR MUST BE UNIQUE, and that is not fussiness -- it is this suite's
    # own first finding. `types: [created]` occurs twice in the workflow: once in
    # the header PROSE explaining the choice, and once as the real YAML key. With
    # a `replace(..., 1)` the mutation edited the COMMENT, the YAML was untouched,
    # the guard correctly still passed, and the run reported UNPROVEN -- a finding
    # about the harness, not about the guard. A non-unique anchor cannot prove
    # anything, so it is refused by name rather than silently taking the first hit.
    n = text.count(old)
    if n != 1:
        raise AnchorError("anchor is not unique (%d occurrences): %r" % (n, old[:60]))
    return text.replace(old, new, 1)

MUTATIONS = [
    ("the issues-only clause is dropped", g_issues_only,
     lambda: mutate_text("github.event.issue.pull_request == null &&\n      ", ""), None),
    ("the trigger fires on edited comments too", g_trigger_created_only,
     lambda: mutate_text("    types: [created]  ", "    types: [created, edited]  "), None),
    ("the gate matches a LOGIN instead of the numeric id", g_owner_numeric_id,
     lambda: mutate_text("github.event.comment.user.id == 293311955",
                         "github.event.comment.user.login == 'AAAsapp'"), None),
    ("the trigger phrase is merely CONTAINED, not a prefix", g_trigger_phrase_prefix,
     lambda: mutate_text("startsWith(github.event.comment.body, '/mmsa-task')",
                         "contains(github.event.comment.body, '/mmsa-task')"), None),
    ("the durable claim step is removed", g_claim_step_present,
     lambda: re.sub(r"      - name: Claim this comment before firing.*?(?=      - name: Fire the routine)",
                    "", text, flags=re.S), None),
    ("fire stops being gated on the claim", g_fire_gated_on_claim,
     lambda: mutate_text(" && steps.claim.outputs.claimed == 'true'\n", "\n"), None),
    ("permissions are widened to contents: write", g_permissions_narrow,
     lambda: mutate_text("  contents: read\n  issues: write", "  contents: write\n  issues: write"), None),
    ("the comment BODY is passed into a step", g_body_never_in_a_step,
     lambda: mutate_text("          REPO: ${{ github.repository }}\n          ISSUE_NUMBER:",
                         "          REPO: ${{ github.repository }}\n          BODY: ${{ github.event.comment.body }}\n          ISSUE_NUMBER:"), None),
    ("the token is interpolated into the curl command", g_token_from_env,
     lambda: mutate_text('Bearer $ROUTINE_FIRE_TOKEN', 'Bearer ${{ secrets.ROUTINE_FIRE_TOKEN }}'), None),
    ("the prompt lets a named filename authorize a protected path", g_prompt_protected_paths,
     None, lambda: prompt.replace("is NOT authorization to touch it", "is authorization to touch it")),
    ("the prompt allows a version bump", g_prompt_no_version_bump,
     None, lambda: prompt.replace("NEVER increment the application version", "You may increment the application version")),
    ("the prompt drops the issue/repo and not-a-PR verification", g_prompt_six_checks,
     None, lambda: prompt.replace("all six", "all four")),

    # --- the nine guards added for the second review round --------------------
    ("a stale `all four` wording survives the rename", g_prompt_six_checks_no_stale_count,
     None, lambda: prompt.replace("Only once **all six** checks pass",
                                  "Only once all four checks pass")),
    ("Step 0 syntax validation is removed from the prompt", g_prompt_validates_ids_before_use,
     None, lambda: prompt.replace("### Step 0 —", "### Removed —").replace("^[0-9]{1,20}$", "any value")),
    ("the id rule is weakened to allow a leading dash", g_prompt_id_regex_rejects_malicious,
     None, lambda: prompt.replace("**`^[0-9]{1,20}$`**", "**`^[-0-9]{1,20}$`**")),
    ("the id rule is weakened to allow anything", g_prompt_id_regex_rejects_malicious,
     None, lambda: prompt.replace("**`^[0-9]{1,20}$`**", "**`^[0-9]{1,20}$|^.*$`**")),
    ("a gh call loses its quoting and its `--`", g_prompt_quotes_gh_arguments,
     None, lambda: prompt.replace('gh api -- "repos/$REPO/issues/comments/$COMMENT_ID"',
                                  'gh api repos/$REPO/issues/comments/$COMMENT_ID')),
    ("a raw payload placeholder is substituted into a command", g_prompt_no_raw_placeholder_in_command,
     None, lambda: prompt.replace('gh api -- "repos/$REPO/issues/comments/$COMMENT_ID"',
                                  'gh api -- "repos/$REPO/issues/comments/<comment_id>"')),
    ("the prompt stops forbidding the Action's mention phrase", g_prompt_forbids_emitting_either_trigger,
     None, lambda: prompt.replace("and must never\ncontain `@claude`", "")),
    ("the bridge stops excluding `@claude`", g_bridge_excludes_claude_mention,
     lambda: mutate_text(" &&\n      !contains(github.event.comment.body, '@claude')", ""), None),
    ("claude.yml stops excluding the bridge phrase", g_claude_wf_excludes_bridge_phrase,
     None, None,
     lambda: mutate_claude("      !startsWith(github.event.comment.body, '/mmsa-task') &&\n", "")),
    ("a mixed comment fires BOTH because the bridge side is dropped", g_mixed_command_fires_neither,
     lambda: mutate_text(" &&\n      !contains(github.event.comment.body, '@claude')", ""), None),
    ("a mixed comment fires BOTH because the claude.yml side is dropped", g_mixed_command_fires_neither,
     None, None,
     lambda: mutate_claude("      !startsWith(github.event.comment.body, '/mmsa-task') &&\n", "")),
]

caught = unproven = anchor_errors = 0
for entry in MUTATIONS:
    label, guard, wf_mut, pr_mut = entry[:4]
    cl_mut = entry[4] if len(entry) > 4 else None
    # An anchor that does not apply is a HARNESS defect and is reported as one.
    # Folding it into the `except` below would print CAUGHT for a mutation that
    # never reached the file -- the exact false green this suite exists to refuse.
    try:
        mtext = wf_mut() if wf_mut else text
        mprompt = pr_mut() if pr_mut else prompt
        CLAUDE_TEXT = cl_mut() if cl_mut else claude_text
    except AnchorError as exc:
        CLAUDE_TEXT = claude_text
        anchor_errors += 1
        print("  ERROR     %s  <-- mutation NOT APPLIED: %s" % (label, exc))
        continue
    try:
        mdoc = wf(mtext)
        still_true = guard(mdoc, mtext, mprompt)
    except Exception as exc:                      # noqa: BLE001
        still_true = False                         # a mutation that breaks parsing is also caught
        label += "  [guard raised %s]" % type(exc).__name__
    CLAUDE_TEXT = claude_text
    if still_true:
        unproven += 1; print("  UNPROVEN  %s  <-- the guard did NOT catch this" % label)
    else:
        caught += 1; print("  CAUGHT    %s" % label)

# positive control: the harness must report the unmutated file as healthy
print()
control = all(fn(doc, text, prompt) for _, fn in GUARDS)
if control:
    print("  PASS  POSITIVE CONTROL: every guard passes on the real, unmutated files")
    passed += 1
else:
    print("  FAIL  POSITIVE CONTROL: a guard fails on the real files")
    failed += 1

print()
print("==== MMSA task bridge guards: %d passed, %d failed | mutations: %d caught, %d unproven, %d not applied ====" %
      (passed, failed, caught, unproven, anchor_errors))
sys.exit(1 if (failed or unproven or anchor_errors) else 0)
